version: '3.0'
services:

sql:
 image: mysql:latest
 environment: 
   - "MQSQL_ROOTS_PASSWORD=secretpass"
 ports: 
   - "3306:3306"
 volumes: 
   - /home/ec2-user/query:/sql

red:
  image: reddis:latest
  volumes: 
    - /home/ec2-user/color:/red


bibox:
  image: busybox:latest
  volumes:
    - /home/ec2-user/box:/bibox

    
